package example1;

import example1.model.drools_group.*;

import java.util.Map;
import java.util.List;
import java.util.ArrayList;
import java.util.Arrays;

rule "no1"
no-loop true
agenda-group "AGENDA1"
salience 9999
when
    $cart :Cart(itemList.size()>0)
then
    System.out.println("=========================>Effected ");
    update($cart);
end

rule "no2"
no-loop true
agenda-group "AGENDA2"
salience 1000
when
    $cart :Cart( itemList.size()>0)
    $item_filter0 :List() from accumulate (
        $filter:Item() from $cart.getItemList(),
        collectList($filter)
  )
then
      update($cart);
end

rule "no3"
no-loop true
agenda-group "AGENDA2"
salience 0
when
    $cart :Cart( itemList.size()>0)
    $spend_filter0 :Number(intValue >= 13000) from accumulate (
        $filter:Item() from $cart.getItemList(),
        sum($filter.price)
  )
then
    update($cart);
end

rule "no4"
no-loop true
agenda-group "AGENDA3"
salience 0
when
    $cart :Cart( itemList.size()>0)
    $spend_filter0 :Number(intValue >= 11000) from accumulate (
        $filter:Item() from $cart.getItemList(),
        sum($filter.price)
  )
then
    update($cart);
end



